name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17  
    - name: Build domain.jar
      run: mvn clean install -f ./domain/pom.xml -X
    - name: Build install.jar
      run: mvn clean install -f ./application/pom.xml -X
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
       username: viniciusll
       password: Kell1@1723
       repository: viniciusll/desafio-btg
       tags: ${{github.run_number}}

